// Central icon vocabulary: every domain concept maps to one lucide icon,
// so the whole UI speaks a single visual language (no emoji in chrome).
import {
  Activity,
  AlertTriangle,
  Biohazard,
  Bird,
  Bot,
  Church,
  CloudLightning,
  Coins,
  Crown,
  Flag,
  Flame,
  FlaskConical,
  Globe2,
  Hand,
  Handshake,
  Haze,
  Hourglass,
  Landmark,
  Lightbulb,
  LucideIcon,
  Map as MapIcon,
  Megaphone,
  Moon,
  Mountain,
  Pickaxe,
  Rocket,
  Scale,
  ScrollText,
  Shield,
  Skull,
  Sparkles,
  Split,
  Sprout,
  Sun,
  Sunrise,
  Swords,
  Tent,
  TreePine,
  TrendingDown,
  Users,
  Waves,
  Wheat,
  Zap,
} from 'lucide-react';
import { WorldEventType } from '../simulation/types';

export const EVENT_ICONS: Partial<Record<WorldEventType, LucideIcon>> = {
  birth: Sprout,
  'city-founded': Landmark,
  'city-captured': Flag,
  technology: Lightbulb,
  war: Swords,
  peace: Bird,
  trade: Coins,
  migration: Users,
  revolution: Megaphone,
  split: Split,
  collapse: TrendingDown,
  extinction: Skull,
  disaster: AlertTriangle,
  alliance: Handshake,
  empire: Crown,
  divine: Zap,
  prayer: Church,
  faith: Church,
  philosophy: ScrollText,
  ascension: Rocket,
};

export const GOD_TOOL_ICONS: Record<string, LucideIcon> = {
  meteor: Flame,
  plague: Biohazard,
  quake: Activity,
  blight: Haze,
  bless: Sparkles,
  spawnCiv: Tent,
  goldenAge: Sun,
  inciteWar: Swords,
  forcePeace: Bird,
};

export const RESOURCE_ICONS: Record<string, LucideIcon> = {
  food: Wheat,
  wood: TreePine,
  stone: Mountain,
  iron: Pickaxe,
  gold: Coins,
};

export const DOCTRINE_ICONS: Record<string, LucideIcon> = {
  harvest: Wheat,
  storm: CloudLightning,
  void: Moon,
  gold: Scale,
  ash: Flame,
  war: Swords,
};

export const ACHIEVEMENT_ICONS: Record<string, LucideIcon> = {
  genesis: Globe2,
  'first-city': Landmark,
  'first-war': Swords,
  empire: Crown,
  schism: Split,
  extinction: Skull,
  ai: Bot,
  'deep-time': Hourglass,
  dominator: MapIcon,
  'last-standing': Flag,
  phoenix: Sunrise,
  'hand-of-god': Hand,
  armageddon: Flame,
  peacemaker: Bird,
  gardener: Sprout,
  'world-at-war': Globe2,
  stellar: Rocket,
  ascension: Sparkles,
};

export const SCENARIO_ICONS: Record<string, LucideIcon> = {
  guardian: Shield,
  arsonist: Flame,
  accelerationist: Rocket,
  worldmother: Tent,
  'silent-god': Moon,
  ark: Waves,
};

export const STAT_ICONS = {
  population: Users,
  civs: Flag,
  cities: Landmark,
  wars: Swords,
  alliances: Handshake,
  tech: Lightbulb,
  science: FlaskConical,
};
